---
abstract: 'Object-Oriented interface for'
author:
  - 'Robert Bohne, C<< <rbo at cpan.org> >>'
  - 'Robert Bohne <rbo@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.36
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Monitoring-Livestatus-Class
no_index:
  directory:
    - inc
    - t
requires:
  Class::Load: 0
  Module::Find: 0
  Monitoring::Livestatus: 0.54
  Moose: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/rbo/Monitoring-Livestatus-Class
version: 0.06
